export const ADD_BOOK_TO_INVENTORY_REQUESTED = 'ADD_BOOK_TO_INVENTORY_REQUESTED';
export const ADD_BOOK_TO_INVENTORY_SUCCESS = 'ADD_BOOK_TO_INVENTORY_SUCCESS';
export const ADD_BOOK_TO_INVENTORY_FAILED = 'ADD_BOOK_TO_INVENTORY_FAILED';

export const GET_ALL_BOOKS_FROM_INVENTORY_REQUESTED = 'GET_ALL_BOOKS_FROM_INVENTORY_REQUESTED';
export const GET_ALL_BOOKS_FROM_INVENTORY_SUCCESS = 'GET_ALL_BOOKS_FROM_INVENTORY_SUCCESS';
export const GET_ALL_BOOKS_FROM_INVENTORY_FAILED = 'GET_ALL_BOOKS_FROM_INVENTORY_FAILED';

export const DELETE_BOOK_FROM_INVENTORY_REQUESTED = 'DELETE_BOOK_FROM_INVENTORY_REQUESTED';
export const DELETE_BOOK_FROM_INVENTORY_SUCCESS = 'DELETE_BOOK_FROM_INVENTORY_SUCCESS';
export const DELETE_BOOK_FROM_INVENTORY_FAILED = 'DELETE_BOOK_FROM_INVENTORY_FAILED';

export const UPDATE_BOOK_FROM_INVENTORY_REQUESTED = 'UPDATE_BOOK_FROM_INVENTORY_REQUESTED';
export const UPDATE_BOOK_FROM_INVENTORY_SUCCESS = 'UPDATE_BOOK_FROM_INVENTORY_SUCCESS';
export const UPDATE_BOOK_FROM_INVENTORY_FAILED = 'UPDATE_BOOK_FROM_INVENTORY_FAILED';

export const ADJUST_STOCK_REQUESTED = 'ADJUST_STOCK_REQUESTED';
export const ADJUST_STOCK_SUCCESS = 'ADJUST_STOCK_SUCCESS';
export const ADJUST_STOCK_FAILED = 'ADJUST_STOCK_FAILED';